"""OpenVPN adapter: own easy-rsa PKI, UDP + TCP servers, username/password auth checked against the panel DB.

WS/WSS for OpenVPN is intentionally NOT in Phase 1 (plan: only if the architecture supports it).
It can be added later by pointing adapters/ssh/ws_tunnel.py at 127.0.0.1:1194/tcp and adding an nginx location.
"""
import os
import re
import shutil

from backend import config, db, servicemgr, shell
from adapters.base import Adapter, AdapterError, apt_install, ensure_nat, listening, port_free, write_file
from adapters.openvpn import status as ovpn_status

PORT = 1194
VARIANTS = {            # proto -> (subnet, unit instance)
    "udp": ("10.8.0.0", "uvpn-udp"),
    "tcp": ("10.9.0.0", "uvpn-tcp"),
}

SERVER_CONF = """# managed by unified-vpn - do not edit (regenerated by the adapter)
port {port}
proto {proto}
dev tun
topology subnet
server {subnet} 255.255.255.0
ca {pki}/pki/ca.crt
cert {pki}/pki/issued/server.crt
key {pki}/pki/private/server.key
dh none
ecdh-curve prime256v1
tls-crypt {pki}/tc.key
tls-version-min 1.2
verify-client-cert none
username-as-common-name
auth-user-pass-verify {scripts}/ovpn-auth.py via-env
script-security 2
cipher AES-256-GCM
auth SHA256
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 1.1.1.1"
push "dhcp-option DNS 8.8.8.8"
keepalive 10 120
max-clients 1000
persist-key
persist-tun
status {varlog}/openvpn/uvpn-{variant}-status.log 10
log-append {varlog}/openvpn/uvpn-{variant}.log
verb 3
{extra}"""

CLIENT_CONF = """client
dev tun
proto {proto}
remote {host} {port}
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
auth-user-pass
cipher AES-256-GCM
auth SHA256
verb 3
<ca>
{ca}
</ca>
<tls-crypt>
{tc}
</tls-crypt>
"""


class OpenVPNAdapter(Adapter):
    name = "openvpn"
    label = "OpenVPN"
    protocols = ("openvpn",)

    @property
    def services(self):
        return tuple("openvpn-server@%s.service" % inst for _, inst in VARIANTS.values())

    @property
    def pki(self):
        return os.path.join(config.ETC, "openvpn/uvpn-pki")

    # ---- install -------------------------------------------------------------
    def _build_pki(self):
        pki = self.pki
        if os.path.exists(os.path.join(pki, "pki/ca.crt")):
            return
        src = "/usr/share/easy-rsa"
        if not os.path.isdir(src):
            raise AdapterError("easy-rsa not found at %s" % src)
        if not os.path.isdir(pki):
            shutil.copytree(src, pki, symlinks=True)
        env = dict(os.environ, EASYRSA_BATCH="1", EASYRSA_REQ_CN="UnifiedVPN-CA", EASYRSA_PKI=os.path.join(pki, "pki"))
        for args in (["init-pki"], ["build-ca", "nopass"], ["build-server-full", "server", "nopass"]):
            shell.run(["./easyrsa", "--batch"] + args, cwd=pki, env=env, timeout=300, check=True)
        r = shell.run(["openvpn", "--genkey", "secret", os.path.join(pki, "tc.key")])
        if not r.ok:   # OpenVPN < 2.5 syntax
            shell.run(["openvpn", "--genkey", "--secret", os.path.join(pki, "tc.key")], check=True)
        if not config.DRY_RUN:
            os.chmod(os.path.join(pki, "tc.key"), 0o600)
            os.chmod(os.path.join(pki, "pki/private"), 0o700)

    def configure(self):
        os.makedirs(os.path.join(config.VARLOG, "openvpn"), exist_ok=True)
        for variant, (subnet, inst) in VARIANTS.items():
            conf = SERVER_CONF.format(port=PORT, proto=variant, subnet=subnet, pki=self.pki, scripts=config.SCRIPTS_DIR,
                                      varlog=config.VARLOG, variant=variant,
                                      extra="explicit-exit-notify 1\n" if variant == "udp" else "")
            write_file(os.path.join(config.ETC, "openvpn/server/%s.conf" % inst), conf, 0o600)

    def install(self, opts=None):
        for variant in VARIANTS:                    # port check - never kill the owner
            if not port_free(variant, PORT):
                raise AdapterError("%s/%d is already in use; free it or change PORT before installing" % (variant, PORT))
        apt_install("openvpn", "easy-rsa", "iptables")
        self._build_pki()
        self.configure()
        ensure_nat()
        for u in self.services:
            shell.run(["systemctl", "enable", "--now", u], check=True)
        self.mark_installed({"port": PORT})

    def uninstall(self):
        for u in self.services:
            shell.run(["systemctl", "disable", "--now", u])
        shell.run(["systemctl", "disable", "--now", "unified-vpn-nat.service"])
        for inst in [i for _, i in VARIANTS.values()]:
            p = os.path.join(config.ETC, "openvpn/server/%s.conf" % inst)
            if os.path.exists(p):
                os.remove(p)
        p = os.path.join(config.SYSTEMD_DIR, "unified-vpn-nat.service")
        if os.path.exists(p):
            os.remove(p)
        shell.run(["systemctl", "daemon-reload"])
        self.unmark_installed()          # PKI is kept on purpose (certificates are not auto-deleted)

    # ---- users (auth is DB-backed: see scripts/ovpn-auth.py) -----------------------------
    def create_user(self, user, account):
        return {"profiles": sorted(VARIANTS)}

    def revoke_user(self, user, account):
        pass                              # next auth fails because the DB says expired/disabled

    def online(self):
        counts = {}
        for cn, _ in ovpn_status.connected(config.VARLOG):
            counts[cn] = counts.get(cn, 0) + 1
        return counts

    # ---- client config -------------------------------------------------------------------
    def generate_config(self, user, proto, host):
        """Build user.ovpn - refuse to hand out a profile that cannot work."""
        if proto not in VARIANTS:
            raise ValueError("proto must be udp or tcp")
        problems = []
        ca_path, tc_path = os.path.join(self.pki, "pki/ca.crt"), os.path.join(self.pki, "tc.key")
        for p in (ca_path, tc_path):
            if not os.path.exists(p) and not config.DRY_RUN:
                problems.append("missing %s" % p)
        inst = VARIANTS[proto][1]
        if servicemgr.unit_state("openvpn-server@%s.service" % inst) not in ("RUNNING", "UNKNOWN"):
            problems.append("openvpn-%s service is not running" % proto)
        if not listening(proto, PORT):
            problems.append("%s/%d is not listening" % (proto, PORT))
        if problems:
            raise AdapterError("OpenVPN profile not available: " + "; ".join(problems))
        ca = open(ca_path).read().strip() if os.path.exists(ca_path) else ""
        tc = open(tc_path).read().strip() if os.path.exists(tc_path) else ""
        text = CLIENT_CONF.format(proto=proto, host=host, port=PORT, ca=ca, tc=tc)
        if "BEGIN CERTIFICATE" not in text and not config.DRY_RUN:
            raise AdapterError("CA certificate missing from generated profile")
        return "%s-%s.ovpn" % (user["username"], proto), text

    def share(self, user, account, hostinfo):
        return {"links": [], "info": {"host": hostinfo["host"], "port": PORT},
                "files": [{"label": "OpenVPN UDP (.ovpn)", "protocol": "openvpn", "proto": "udp"},
                          {"label": "OpenVPN TCP (.ovpn)", "protocol": "openvpn", "proto": "tcp"}]}

    def info(self):
        return {"port": PORT, "protocols": ["udp", "tcp"]}

    def health(self):
        res = []
        for variant, (_, inst) in VARIANTS.items():
            res.append(("openvpn-%s service active" % variant,
                        servicemgr.unit_state("openvpn-server@%s.service" % inst) in ("RUNNING", "UNKNOWN"), ""))
            res.append(("%s/%d listening" % (variant, PORT), listening(variant, PORT), ""))
        res.append(("PKI present", config.DRY_RUN or os.path.exists(os.path.join(self.pki, "pki/ca.crt")), ""))
        res.append(("auth script present", os.path.exists(os.path.join(config.SCRIPTS_DIR, "ovpn-auth.py")) or config.DRY_RUN, ""))
        return res
